---
development:
  cloud_name: subashsly
  api_key: '799933213172293'
  api_secret: kJ1WdOpfhd4nMgaDfRMoWshl_qk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: subashsly
  api_key: '799933213172293'
  api_secret: kJ1WdOpfhd4nMgaDfRMoWshl_qk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: subashsly
  api_key: '799933213172293'
  api_secret: kJ1WdOpfhd4nMgaDfRMoWshl_qk
  enhance_image_tag: true
  static_image_support: false
